name: Build ISOs

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # manually trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update repo
        run: nix flake update

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build Gnome ISO
        run: |
          nix build
          mv result/iso/nixos-minimal-*-x86_64-linux.iso gnome.iso

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.BUILD_DATE }}
          name: v${{ env.BUILD_DATE }}
          body: |
            Automated release powered by GitHub Actions.
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gnome ISO
        uses: softprops/action-gh-release@v1
        with:
          files: gnome.iso
          name: CosmOS-Gnome-${{ env.BUILD_DATE }}-x86_64.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Hyprland ISO
        uses: softprops/action-gh-release@v1
        with:
          files: hyprland.iso
          name: CosmOS-Hyprland-${{ env.BUILD_DATE }}-x86_64.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
